plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.1.27'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

sourceSets.main.resources {
    srcDir('src/generated/resources')

    exclude("**/*.bbmodel")
    exclude("src/generated/**/.cache")
}

base {
    archivesName = mod_id + "-" + minecraft_version
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

configurations {
    datagenRuntime

    runtimeClasspath.extendsFrom localRuntime
}

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'

        workingDirectory project.layout.projectDirectory.dir('run').dir(name)

        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        argument '--nogui'
    }

    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        arguments.addAll '--mod', project.mod_id, '--all',
                '--output', file('src/generated/resources/').getAbsolutePath(),
                '--existing', file('src/main/resources/').getAbsolutePath()

        runtimeClasspath.from(configurations.datagenRuntime)
    }
}

repositories {
    maven {
        url = "https://www.cursemaven.com"
        content {
            includeGroup("curse.maven")
        }
    }

    maven {
        url = uri("https://api.modrinth.com/maven")
        content {
            includeGroup("maven.modrinth")
        }
    }

    maven { url = "https://maven.createmod.net" }
    maven { url = "https://maven.ithundxr.dev/snapshots" }

    maven {
        url = uri("https://registry.somethingcatchy.net/repository/maven-releases/")
        content {
            includeGroup("com.possible-triangle")
        }
    }

    maven {url = "https://maven.caffeinemc.net/releases"}
    maven {url = "https://maven.blamejared.com/"}
    maven {url = "https://modmaven.dev"}
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
    implementation "curse.maven:blueprint-${blueprint_id}"
    implementation "curse.maven:biolith-${biolith_id}"
    implementation "curse.maven:terrablender-neoforge-${terrablender_id}"
    implementation "curse.maven:geckolib-${geckolib_id}"

    implementation "maven.modrinth:oreganized:${oreganized_ver}"

    compileOnly "maven.modrinth:shield-expansion:${shieldexp_id}"
    datagenRuntime "maven.modrinth:shield-expansion:${shieldexp_id}"

    implementation "curse.maven:copper-age-backport-1386823:7283478"
    implementation "curse.maven:copper-age-backport-duplicate-armor-material-fix-1664466:8710995"

    implementation "maven.modrinth:farmers-delight:${farmersdelight_ver}"
    implementation "curse.maven:backported-spears-1385191:7725067"

    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    compileOnly("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    compileOnly("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    compileOnly("com.tterrag.registrate:Registrate:${registrate_version}")

    datagenRuntime("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    datagenRuntime("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    datagenRuntime("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    datagenRuntime("com.tterrag.registrate:Registrate:${registrate_version}")

    implementation "com.possible-triangle:multikulti-core-neoforge:1.21.1-2.0.1"
    implementation "com.possible-triangle:multikulti-datagen-neoforge:1.21.1-2.0.1"

    implementation "maven.modrinth:sodium:mc1.21.1-0.6.13-neoforge"

    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:19.21.0.247")
    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:19.21.0.247")

    runtimeOnly "curse.maven:shadow-drop-1490601:8491920"

    // runtimeOnly "curse.maven:create-328085:7963363"

    // implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    // implementation("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    // runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    // implementation("com.tterrag.registrate:Registrate:${registrate_version}")
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}